export const AIRDROP_CHECK_ELIGIBILITY = 'AIRDROP_CHECK_ELIGIBILITY';
export const AIRDROP_ELIGIBLE = 'AIRDROP_ELIGIBLE';
export const AIRDROP_NOT_ELIGIBLE = 'AIRDROP_NOT_ELIGIBLE';
export const AIRDROP_FAILURE = 'AIRDROP_FAILURE';

export const AIRDROP_TEST_ELIGIBILITY = 'AIRDROP_TEST_ELIGIBILITY';
export const AIRDROP_IS_ELIGIBLE = 'AIRDROP_IS_ELIGIBLE';
export const AIRDROP_IS_NOT_ELIGIBLE = 'AIRDROP_IS_NOT_ELIGIBLE';
export const AIRDROP_IS_FAILURE = 'AIRDROP_IS_FAILURE';
